version: "3.8"

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:15.0
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - ./.docker/postgres/data/:/var/lib/postgresql/data/:rw
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  mongo_db:
    container_name: mongo_db
    image: mongo:6.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_USER: ${MONGO_INITDB_USER}
      MONGO_INITDB_PWD: ${MONGO_INITDB_PWD}
    ports:
      - $MONGO_PORT:27017
    volumes:
      - ./.docker/mongodb/data/:/data/db/
      # - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      